// Code generated by generate-response-codes/main.go; DO NOT EDIT.

package api2c2p

import "fmt"

// ResponseCode represents a 2C2P response code
type ResponseCode string

// Description returns a human-readable description of the response code
func (c ResponseCode) Description() string {
	switch c {
	case "0000":
		return "Successful"
	case "0001":
		return "Transaction is pending"
	case "0003":
		return "Transaction is cancelled"
	case "0004":
		return "Transaction is soft-declined. Resubmit the transaction after 3ds authentication"
	case "0999":
		return "System error"
	case "2001":
		return "Transaction in progress"
	case "2002":
		return "Transaction not found"
	case "2003":
		return "Failed To Inquiry"
	case "4000":
		return "Card Verification Successful"
	case "4001":
		return "Refer to card issuer"
	case "4002":
		return "Refer to issuer's special conditions"
	case "4003":
		return "Invalid merchant ID"
	case "4004":
		return "Pick up card"
	case "4005":
		return "Do not honor"
	case "4006":
		return "Error"
	case "4007":
		return "Pick up card, special condition"
	case "4008":
		return "Honor with ID"
	case "4009":
		return "Request in progress"
	case "4010":
		return "Partial amount approved"
	case "4011":
		return "Approved VIP"
	case "4012":
		return "Invalid Transaction"
	case "4013":
		return "Invalid Amount"
	case "4014":
		return "Invalid Card Number"
	case "4015":
		return "No such issuer"
	case "4016":
		return "Approved, Update Track 3"
	case "4017":
		return "Customer Cancellation"
	case "4018":
		return "Customer Dispute"
	case "4019":
		return "Re-enter Transaction"
	case "4020":
		return "Invalid Response"
	case "4021":
		return "No Action Taken"
	case "4022":
		return "Suspected Malfunction"
	case "4023":
		return "Unacceptable Transaction Fee"
	case "4024":
		return "File Update Not Supported by Receiver"
	case "4025":
		return "Unable to Locate Record on File"
	case "4026":
		return "Duplicate File Update Record"
	case "4027":
		return "File Update Field Edit Error"
	case "4028":
		return "File Update File Locked Out"
	case "4029":
		return "File Update not Successful"
	case "4030":
		return "Format Error"
	case "4031":
		return "Bank Not Supported by Switch"
	case "4032":
		return "Completed Partially"
	case "4033":
		return "Expired Card - Pick Up"
	case "4034":
		return "Suspected Fraud - Pick Up"
	case "4035":
		return "Restricted Card - Pick Up"
	case "4036":
		return "Allowable PIN Tries Exceeded"
	case "4037":
		return "No Credit Account"
	case "4038":
		return "Allowable PIN Tries Exceeded"
	case "4039":
		return "No Credit Account"
	case "4040":
		return "Requested Function not Supported"
	case "4041":
		return "Lost Card - Pick Up"
	case "4042":
		return "No Universal Amount"
	case "4043":
		return "Stolen Card - Pick Up"
	case "4044":
		return "No Investment Account"
	case "4045":
		return "Settlement Success"
	case "4046":
		return "Settlement Fail"
	case "4047":
		return "Cancel Success"
	case "4048":
		return "Cancel Fail"
	case "4049":
		return "No Transaction Reference Number"
	case "4050":
		return "Host Down"
	case "4051":
		return "Insufficient Funds"
	case "4052":
		return "No Cheque Account"
	case "4053":
		return "No Savings Account"
	case "4054":
		return "Expired Card"
	case "4055":
		return "Incorrect PIN"
	case "4056":
		return "No Card Record"
	case "4057":
		return "Transaction Not Permitted to Cardholder"
	case "4058":
		return "Transaction Not Permitted to Terminal"
	case "4059":
		return "Suspected Fraud"
	case "4060":
		return "Card Acceptor Contact Acquirer"
	case "4061":
		return "Exceeds Withdrawal Amount Limits"
	case "4062":
		return "Restricted Card"
	case "4063":
		return "Security Violation"
	case "4064":
		return "Original Amount Incorrect"
	case "4065":
		return "Exceeds Withdrawal Frequency Limit"
	case "4066":
		return "Card Acceptor Call Acquirer Security"
	case "4067":
		return "Hard Capture - Pick Up Card at ATM"
	case "4068":
		return "Response Received Too Late"
	case "4069":
		return "Reserved"
	case "4070":
		return "Settle amount cannot exceed authorized amount"
	case "4071":
		return "Inquiry Record Not Exist"
	case "4072":
		return "Promotion not allowed in current payment method"
	case "4073":
		return "Promotion Limit Reached"
	case "4074":
		return "Reserved"
	case "4075":
		return "Allowable PIN Tries Exceeded"
	case "4076":
		return "Invalid Credit Card Format"
	case "4077":
		return "Invalid Expiry Date Format"
	case "4078":
		return "Invalid Three Digits Format"
	case "4079":
		return "Reserved"
	case "4080":
		return "User Cancellation by Closing Internet Browser"
	case "4081":
		return "Unable to Authenticate Card Holder"
	case "4082":
		return "Reserved"
	case "4083":
		return "Reserved"
	case "4084":
		return "Reserved"
	case "4085":
		return "Reserved"
	case "4086":
		return "ATM Malfunction"
	case "4087":
		return "No Envelope Inserted"
	case "4088":
		return "Unable to Dispense"
	case "4089":
		return "Administration Error"
	case "4090":
		return "Cut-off in Progress"
	case "4091":
		return "Issuer or Switch is Inoperative"
	case "4092":
		return "Financial Insititution Not Found"
	case "4093":
		return "Trans Cannot Be Completed"
	case "4094":
		return "Duplicate Transmission"
	case "4095":
		return "Reconcile Error"
	case "4096":
		return "System Malfunction"
	case "4097":
		return "Reconciliation Totals Reset"
	case "4098":
		return "MAC Error"
	case "4099":
		return "Unable to Complete Payment"
	case "4110":
		return "Settled"
	case "4120":
		return "Refunded"
	case "4121":
		return "Refund Rejected"
	case "4122":
		return "Refund Failed"
	case "4130":
		return "Chargeback"
	case "4131":
		return "Chargeback Rejected"
	case "4132":
		return "Chargeback Failed"
	case "4140":
		return "Transaction Does Not Exist"
	case "4200":
		return "Tokenization Successful"
	case "4201":
		return "Tokenization Failed"
	case "4202":
		return "Invalid Card / Customer Token"
	case "4203":
		return "No response from account issuer"
	case "4204":
		return "Tokenization Action Failed (Token)"
	case "4205":
		return "Tokenization Action Failed (Limit Exceed)"
	case "4208":
		return "Tokenization Action Failed (Client)"
	case "4209":
		return "Tokenization Action Failed  (Issuer)"
	case "5002":
		return "Timeout"
	case "5003":
		return "Invalid Message"
	case "5004":
		return "Invalid Profile (Merchant) ID"
	case "5005":
		return "Duplicated Invoice"
	case "5006":
		return "Invalid Amount"
	case "5007":
		return "Insufficient Balance"
	case "5008":
		return "Invalid Currency Code"
	case "5009":
		return "Payment Expired"
	case "5010":
		return "Payment Canceled By Payer"
	case "5011":
		return "Invalid Payee ID"
	case "5012":
		return "Invalid Customer ID"
	case "5013":
		return "Account Does Not Exist"
	case "5014":
		return "Authentication Failed"
	case "5015":
		return "Customer paid more than transaction amount"
	case "5016":
		return "Customer paid less than transaction amount"
	case "5017":
		return "Paid Expired"
	case "5018":
		return "Reserved"
	case "5019":
		return "No-Action From WebPay"
	case "5998":
		return "Internal Error"
	case "6012":
		return "Invalid Transaction"
	case "6101":
		return "Invalid request message"
	case "6102":
		return "Required Payload"
	case "6103":
		return "Invalid JWT data"
	case "6104":
		return "Required merchantId"
	case "6105":
		return "Required paymentChannel"
	case "6106":
		return "Required authCode"
	case "6107":
		return "Invalid merchantId"
	case "6108":
		return "Invalid paymentChannel"
	case "6109":
		return "paymentChannel is not configured"
	case "6110":
		return "Unable to retrieve usertoken"
	case "7012":
		return "Invalid Transaction"
	case "9004":
		return "The [ParameterName] value is not valid"
	case "9005":
		return "Some mandatory fields are missing"
	case "9006":
		return "This field exceeded its authorized length"
	case "9007":
		return "Invalid merchant"
	case "9008":
		return "Invalid payment expiry"
	case "9009":
		return "Amount is invalid"
	case "9010":
		return "Invalid Currency Code"
	case "9012":
		return "paymentItem name is required"
	case "9013":
		return "paymentItem quantity is required"
	case "9014":
		return "paymentItem amount is required"
	case "9015":
		return "Existing Invoice Number"
	case "9016":
		return "Failed to retrieve PaymentInstruction"
	case "9017":
		return "PaymentInstruction not available"
	case "9035":
		return "Payment failed"
	case "9037":
		return "Merchant configuration is missing"
	case "9038":
		return "Failed To Generate Token"
	case "9039":
		return "The merchant frontend URL is missing"
	case "9040":
		return "The token is invalid"
	case "9041":
		return "Payment token already used"
	case "9042":
		return "Hash value mismatch"
	case "9057":
		return "Payment options are invalid"
	case "9058":
		return "Payment channel invalid"
	case "9059":
		return "Payment channel unauthorized"
	case "9060":
		return "Payment channel unconfigured"
	case "9078":
		return "Promotion code does not exist"
	case "9080":
		return "Tokenization not allowed"
	case "9088":
		return "SubMerchant is required"
	case "9089":
		return "Duplicated SubMerchant"
	case "9090":
		return "SubMerchant Not Found"
	case "9091":
		return "Invalid Sub Merchant ID"
	case "9092":
		return "Invalid Sub Merchant invoiceNo"
	case "9093":
		return "Existing Sub Merchant Invoice Number"
	case "9094":
		return "Invalid Sub Merchant Amount"
	case "9095":
		return "Sub Merchant Amount mismatch"
	case "9100":
		return "FxRateId and OriginalAmount are required"
	case "9101":
		return "Not allow to make a payment with Fx"
	case "9102":
		return "FxRate not available"
	case "9103":
		return "Invalid amount. (for the transaction which using the FxRateId)"
	case "9104":
		return "Invalid Country Code (Airline Info)"
	case "9105":
		return "Invalid Currency Code (Airline Info)"
	case "9106":
		return "Invalid Loyalty Redeem Amount"
	case "9107":
		return "Invalid Loyalty Provider"
	case "9108":
		return "Duplicated Loyalty Reward Id"
	case "9109":
		return "Required Loyalty's External Merchant Id"
	case "9110":
		return "Failed to Inquiry Loyalty Rewards"
	case "9202":
		return "Invalid CustomerToken"
	case "9900":
		return "Unable to decrypt the payload"
	case "9901":
		return "Invalid invoicePrefix"
	case "9902":
		return "allowAccumulate is required"
	case "9903":
		return "maxAccumulateAmount is required"
	case "9904":
		return "recurringInterval or ChargeOnDate is required"
	case "9905":
		return "recurringCount is required"
	case "9906":
		return "recurringInterval or ChargeOnDate is required"
	case "9907":
		return "Invalid ChargeNextDate"
	case "9908":
		return "Invalid ChargeOnDate"
	case "9909":
		return "chargeNextDate is required"
	case "9990":
		return "Request to merchant front end has failed"
	case "9991":
		return "Request merchant secure has failed"
	case "9992":
		return "Request payment secure has failed"
	case "9993":
		return "An unknown error has occured"
	case "9994":
		return "Request DB service has failed"
	case "9995":
		return "Request payment service has failed"
	case "9996":
		return "Request Qwik service has failed"
	case "9997":
		return "Request user preferences has failed"
	case "9998":
		return "Request store card has failed"
	case "9999":
		return "Request to merchant backend has failed"
	default:
		return fmt.Sprintf("Unknown response code: %s", string(c))
	}
}

// Known response codes
const (
	RespCode0000 ResponseCode = "0000" // Successful
	RespCode0001 ResponseCode = "0001" // Transaction is pending
	RespCode0003 ResponseCode = "0003" // Transaction is cancelled
	RespCode0004 ResponseCode = "0004" // Transaction is soft-declined. Resubmit the transaction after 3ds authentication
	RespCode0999 ResponseCode = "0999" // System error
	RespCode2001 ResponseCode = "2001" // Transaction in progress
	RespCode2002 ResponseCode = "2002" // Transaction not found
	RespCode2003 ResponseCode = "2003" // Failed To Inquiry
	RespCode4000 ResponseCode = "4000" // Card Verification Successful
	RespCode4001 ResponseCode = "4001" // Refer to card issuer
	RespCode4002 ResponseCode = "4002" // Refer to issuer's special conditions
	RespCode4003 ResponseCode = "4003" // Invalid merchant ID
	RespCode4004 ResponseCode = "4004" // Pick up card
	RespCode4005 ResponseCode = "4005" // Do not honor
	RespCode4006 ResponseCode = "4006" // Error
	RespCode4007 ResponseCode = "4007" // Pick up card, special condition
	RespCode4008 ResponseCode = "4008" // Honor with ID
	RespCode4009 ResponseCode = "4009" // Request in progress
	RespCode4010 ResponseCode = "4010" // Partial amount approved
	RespCode4011 ResponseCode = "4011" // Approved VIP
	RespCode4012 ResponseCode = "4012" // Invalid Transaction
	RespCode4013 ResponseCode = "4013" // Invalid Amount
	RespCode4014 ResponseCode = "4014" // Invalid Card Number
	RespCode4015 ResponseCode = "4015" // No such issuer
	RespCode4016 ResponseCode = "4016" // Approved, Update Track 3
	RespCode4017 ResponseCode = "4017" // Customer Cancellation
	RespCode4018 ResponseCode = "4018" // Customer Dispute
	RespCode4019 ResponseCode = "4019" // Re-enter Transaction
	RespCode4020 ResponseCode = "4020" // Invalid Response
	RespCode4021 ResponseCode = "4021" // No Action Taken
	RespCode4022 ResponseCode = "4022" // Suspected Malfunction
	RespCode4023 ResponseCode = "4023" // Unacceptable Transaction Fee
	RespCode4024 ResponseCode = "4024" // File Update Not Supported by Receiver
	RespCode4025 ResponseCode = "4025" // Unable to Locate Record on File
	RespCode4026 ResponseCode = "4026" // Duplicate File Update Record
	RespCode4027 ResponseCode = "4027" // File Update Field Edit Error
	RespCode4028 ResponseCode = "4028" // File Update File Locked Out
	RespCode4029 ResponseCode = "4029" // File Update not Successful
	RespCode4030 ResponseCode = "4030" // Format Error
	RespCode4031 ResponseCode = "4031" // Bank Not Supported by Switch
	RespCode4032 ResponseCode = "4032" // Completed Partially
	RespCode4033 ResponseCode = "4033" // Expired Card - Pick Up
	RespCode4034 ResponseCode = "4034" // Suspected Fraud - Pick Up
	RespCode4035 ResponseCode = "4035" // Restricted Card - Pick Up
	RespCode4036 ResponseCode = "4036" // Allowable PIN Tries Exceeded
	RespCode4037 ResponseCode = "4037" // No Credit Account
	RespCode4038 ResponseCode = "4038" // Allowable PIN Tries Exceeded
	RespCode4039 ResponseCode = "4039" // No Credit Account
	RespCode4040 ResponseCode = "4040" // Requested Function not Supported
	RespCode4041 ResponseCode = "4041" // Lost Card - Pick Up
	RespCode4042 ResponseCode = "4042" // No Universal Amount
	RespCode4043 ResponseCode = "4043" // Stolen Card - Pick Up
	RespCode4044 ResponseCode = "4044" // No Investment Account
	RespCode4045 ResponseCode = "4045" // Settlement Success
	RespCode4046 ResponseCode = "4046" // Settlement Fail
	RespCode4047 ResponseCode = "4047" // Cancel Success
	RespCode4048 ResponseCode = "4048" // Cancel Fail
	RespCode4049 ResponseCode = "4049" // No Transaction Reference Number
	RespCode4050 ResponseCode = "4050" // Host Down
	RespCode4051 ResponseCode = "4051" // Insufficient Funds
	RespCode4052 ResponseCode = "4052" // No Cheque Account
	RespCode4053 ResponseCode = "4053" // No Savings Account
	RespCode4054 ResponseCode = "4054" // Expired Card
	RespCode4055 ResponseCode = "4055" // Incorrect PIN
	RespCode4056 ResponseCode = "4056" // No Card Record
	RespCode4057 ResponseCode = "4057" // Transaction Not Permitted to Cardholder
	RespCode4058 ResponseCode = "4058" // Transaction Not Permitted to Terminal
	RespCode4059 ResponseCode = "4059" // Suspected Fraud
	RespCode4060 ResponseCode = "4060" // Card Acceptor Contact Acquirer
	RespCode4061 ResponseCode = "4061" // Exceeds Withdrawal Amount Limits
	RespCode4062 ResponseCode = "4062" // Restricted Card
	RespCode4063 ResponseCode = "4063" // Security Violation
	RespCode4064 ResponseCode = "4064" // Original Amount Incorrect
	RespCode4065 ResponseCode = "4065" // Exceeds Withdrawal Frequency Limit
	RespCode4066 ResponseCode = "4066" // Card Acceptor Call Acquirer Security
	RespCode4067 ResponseCode = "4067" // Hard Capture - Pick Up Card at ATM
	RespCode4068 ResponseCode = "4068" // Response Received Too Late
	RespCode4069 ResponseCode = "4069" // Reserved
	RespCode4070 ResponseCode = "4070" // Settle amount cannot exceed authorized amount
	RespCode4071 ResponseCode = "4071" // Inquiry Record Not Exist
	RespCode4072 ResponseCode = "4072" // Promotion not allowed in current payment method
	RespCode4073 ResponseCode = "4073" // Promotion Limit Reached
	RespCode4074 ResponseCode = "4074" // Reserved
	RespCode4075 ResponseCode = "4075" // Allowable PIN Tries Exceeded
	RespCode4076 ResponseCode = "4076" // Invalid Credit Card Format
	RespCode4077 ResponseCode = "4077" // Invalid Expiry Date Format
	RespCode4078 ResponseCode = "4078" // Invalid Three Digits Format
	RespCode4079 ResponseCode = "4079" // Reserved
	RespCode4080 ResponseCode = "4080" // User Cancellation by Closing Internet Browser
	RespCode4081 ResponseCode = "4081" // Unable to Authenticate Card Holder
	RespCode4082 ResponseCode = "4082" // Reserved
	RespCode4083 ResponseCode = "4083" // Reserved
	RespCode4084 ResponseCode = "4084" // Reserved
	RespCode4085 ResponseCode = "4085" // Reserved
	RespCode4086 ResponseCode = "4086" // ATM Malfunction
	RespCode4087 ResponseCode = "4087" // No Envelope Inserted
	RespCode4088 ResponseCode = "4088" // Unable to Dispense
	RespCode4089 ResponseCode = "4089" // Administration Error
	RespCode4090 ResponseCode = "4090" // Cut-off in Progress
	RespCode4091 ResponseCode = "4091" // Issuer or Switch is Inoperative
	RespCode4092 ResponseCode = "4092" // Financial Insititution Not Found
	RespCode4093 ResponseCode = "4093" // Trans Cannot Be Completed
	RespCode4094 ResponseCode = "4094" // Duplicate Transmission
	RespCode4095 ResponseCode = "4095" // Reconcile Error
	RespCode4096 ResponseCode = "4096" // System Malfunction
	RespCode4097 ResponseCode = "4097" // Reconciliation Totals Reset
	RespCode4098 ResponseCode = "4098" // MAC Error
	RespCode4099 ResponseCode = "4099" // Unable to Complete Payment
	RespCode4110 ResponseCode = "4110" // Settled
	RespCode4120 ResponseCode = "4120" // Refunded
	RespCode4121 ResponseCode = "4121" // Refund Rejected
	RespCode4122 ResponseCode = "4122" // Refund Failed
	RespCode4130 ResponseCode = "4130" // Chargeback
	RespCode4131 ResponseCode = "4131" // Chargeback Rejected
	RespCode4132 ResponseCode = "4132" // Chargeback Failed
	RespCode4140 ResponseCode = "4140" // Transaction Does Not Exist
	RespCode4200 ResponseCode = "4200" // Tokenization Successful
	RespCode4201 ResponseCode = "4201" // Tokenization Failed
	RespCode4202 ResponseCode = "4202" // Invalid Card / Customer Token
	RespCode4203 ResponseCode = "4203" // No response from account issuer
	RespCode4204 ResponseCode = "4204" // Tokenization Action Failed (Token)
	RespCode4205 ResponseCode = "4205" // Tokenization Action Failed (Limit Exceed)
	RespCode4208 ResponseCode = "4208" // Tokenization Action Failed (Client)
	RespCode4209 ResponseCode = "4209" // Tokenization Action Failed  (Issuer)
	RespCode5002 ResponseCode = "5002" // Timeout
	RespCode5003 ResponseCode = "5003" // Invalid Message
	RespCode5004 ResponseCode = "5004" // Invalid Profile (Merchant) ID
	RespCode5005 ResponseCode = "5005" // Duplicated Invoice
	RespCode5006 ResponseCode = "5006" // Invalid Amount
	RespCode5007 ResponseCode = "5007" // Insufficient Balance
	RespCode5008 ResponseCode = "5008" // Invalid Currency Code
	RespCode5009 ResponseCode = "5009" // Payment Expired
	RespCode5010 ResponseCode = "5010" // Payment Canceled By Payer
	RespCode5011 ResponseCode = "5011" // Invalid Payee ID
	RespCode5012 ResponseCode = "5012" // Invalid Customer ID
	RespCode5013 ResponseCode = "5013" // Account Does Not Exist
	RespCode5014 ResponseCode = "5014" // Authentication Failed
	RespCode5015 ResponseCode = "5015" // Customer paid more than transaction amount
	RespCode5016 ResponseCode = "5016" // Customer paid less than transaction amount
	RespCode5017 ResponseCode = "5017" // Paid Expired
	RespCode5018 ResponseCode = "5018" // Reserved
	RespCode5019 ResponseCode = "5019" // No-Action From WebPay
	RespCode5998 ResponseCode = "5998" // Internal Error
	RespCode6012 ResponseCode = "6012" // Invalid Transaction
	RespCode6101 ResponseCode = "6101" // Invalid request message
	RespCode6102 ResponseCode = "6102" // Required Payload
	RespCode6103 ResponseCode = "6103" // Invalid JWT data
	RespCode6104 ResponseCode = "6104" // Required merchantId
	RespCode6105 ResponseCode = "6105" // Required paymentChannel
	RespCode6106 ResponseCode = "6106" // Required authCode
	RespCode6107 ResponseCode = "6107" // Invalid merchantId
	RespCode6108 ResponseCode = "6108" // Invalid paymentChannel
	RespCode6109 ResponseCode = "6109" // paymentChannel is not configured
	RespCode6110 ResponseCode = "6110" // Unable to retrieve usertoken
	RespCode7012 ResponseCode = "7012" // Invalid Transaction
	RespCode9004 ResponseCode = "9004" // The [ParameterName] value is not valid
	RespCode9005 ResponseCode = "9005" // Some mandatory fields are missing
	RespCode9006 ResponseCode = "9006" // This field exceeded its authorized length
	RespCode9007 ResponseCode = "9007" // Invalid merchant
	RespCode9008 ResponseCode = "9008" // Invalid payment expiry
	RespCode9009 ResponseCode = "9009" // Amount is invalid
	RespCode9010 ResponseCode = "9010" // Invalid Currency Code
	RespCode9012 ResponseCode = "9012" // paymentItem name is required
	RespCode9013 ResponseCode = "9013" // paymentItem quantity is required
	RespCode9014 ResponseCode = "9014" // paymentItem amount is required
	RespCode9015 ResponseCode = "9015" // Existing Invoice Number
	RespCode9016 ResponseCode = "9016" // Failed to retrieve PaymentInstruction
	RespCode9017 ResponseCode = "9017" // PaymentInstruction not available
	RespCode9035 ResponseCode = "9035" // Payment failed
	RespCode9037 ResponseCode = "9037" // Merchant configuration is missing
	RespCode9038 ResponseCode = "9038" // Failed To Generate Token
	RespCode9039 ResponseCode = "9039" // The merchant frontend URL is missing
	RespCode9040 ResponseCode = "9040" // The token is invalid
	RespCode9041 ResponseCode = "9041" // Payment token already used
	RespCode9042 ResponseCode = "9042" // Hash value mismatch
	RespCode9057 ResponseCode = "9057" // Payment options are invalid
	RespCode9058 ResponseCode = "9058" // Payment channel invalid
	RespCode9059 ResponseCode = "9059" // Payment channel unauthorized
	RespCode9060 ResponseCode = "9060" // Payment channel unconfigured
	RespCode9078 ResponseCode = "9078" // Promotion code does not exist
	RespCode9080 ResponseCode = "9080" // Tokenization not allowed
	RespCode9088 ResponseCode = "9088" // SubMerchant is required
	RespCode9089 ResponseCode = "9089" // Duplicated SubMerchant
	RespCode9090 ResponseCode = "9090" // SubMerchant Not Found
	RespCode9091 ResponseCode = "9091" // Invalid Sub Merchant ID
	RespCode9092 ResponseCode = "9092" // Invalid Sub Merchant invoiceNo
	RespCode9093 ResponseCode = "9093" // Existing Sub Merchant Invoice Number
	RespCode9094 ResponseCode = "9094" // Invalid Sub Merchant Amount
	RespCode9095 ResponseCode = "9095" // Sub Merchant Amount mismatch
	RespCode9100 ResponseCode = "9100" // FxRateId and OriginalAmount are required
	RespCode9101 ResponseCode = "9101" // Not allow to make a payment with Fx
	RespCode9102 ResponseCode = "9102" // FxRate not available
	RespCode9103 ResponseCode = "9103" // Invalid amount. (for the transaction which using the FxRateId)
	RespCode9104 ResponseCode = "9104" // Invalid Country Code (Airline Info)
	RespCode9105 ResponseCode = "9105" // Invalid Currency Code (Airline Info)
	RespCode9106 ResponseCode = "9106" // Invalid Loyalty Redeem Amount
	RespCode9107 ResponseCode = "9107" // Invalid Loyalty Provider
	RespCode9108 ResponseCode = "9108" // Duplicated Loyalty Reward Id
	RespCode9109 ResponseCode = "9109" // Required Loyalty's External Merchant Id
	RespCode9110 ResponseCode = "9110" // Failed to Inquiry Loyalty Rewards
	RespCode9202 ResponseCode = "9202" // Invalid CustomerToken
	RespCode9900 ResponseCode = "9900" // Unable to decrypt the payload
	RespCode9901 ResponseCode = "9901" // Invalid invoicePrefix
	RespCode9902 ResponseCode = "9902" // allowAccumulate is required
	RespCode9903 ResponseCode = "9903" // maxAccumulateAmount is required
	RespCode9904 ResponseCode = "9904" // recurringInterval or ChargeOnDate is required
	RespCode9905 ResponseCode = "9905" // recurringCount is required
	RespCode9906 ResponseCode = "9906" // recurringInterval or ChargeOnDate is required
	RespCode9907 ResponseCode = "9907" // Invalid ChargeNextDate
	RespCode9908 ResponseCode = "9908" // Invalid ChargeOnDate
	RespCode9909 ResponseCode = "9909" // chargeNextDate is required
	RespCode9990 ResponseCode = "9990" // Request to merchant front end has failed
	RespCode9991 ResponseCode = "9991" // Request merchant secure has failed
	RespCode9992 ResponseCode = "9992" // Request payment secure has failed
	RespCode9993 ResponseCode = "9993" // An unknown error has occured
	RespCode9994 ResponseCode = "9994" // Request DB service has failed
	RespCode9995 ResponseCode = "9995" // Request payment service has failed
	RespCode9996 ResponseCode = "9996" // Request Qwik service has failed
	RespCode9997 ResponseCode = "9997" // Request user preferences has failed
	RespCode9998 ResponseCode = "9998" // Request store card has failed
	RespCode9999 ResponseCode = "9999" // Request to merchant backend has failed
)
