// Code generated by generate-response-codes/main.go; DO NOT EDIT.

package api2c2p

import "fmt"

// PaymentResponseCode represents a 2C2P response code
type PaymentResponseCode string

// Description returns a human-readable description of the response code
func (c PaymentResponseCode) Description() string {
	switch c {
	case "0000":
		return "Successful"
	case "0001":
		return "Transaction is pending"
	case "0003":
		return "Transaction is cancelled"
	case "0004":
		return "Transaction is soft-declined. Resubmit the transaction after 3ds authentication"
	case "0999":
		return "System error"
	case "2001":
		return "Transaction in progress"
	case "2002":
		return "Transaction not found"
	case "2003":
		return "Failed To Inquiry"
	case "4000":
		return "Card Verification Successful"
	case "4001":
		return "Refer to card issuer"
	case "4002":
		return "Refer to issuer's special conditions"
	case "4003":
		return "Invalid merchant ID"
	case "4004":
		return "Pick up card"
	case "4005":
		return "Do not honor"
	case "4006":
		return "Error"
	case "4007":
		return "Pick up card, special condition"
	case "4008":
		return "Honor with ID"
	case "4009":
		return "Request in progress"
	case "4010":
		return "Partial amount approved"
	case "4011":
		return "Approved VIP"
	case "4012":
		return "Invalid Transaction"
	case "4013":
		return "Invalid Amount"
	case "4014":
		return "Invalid Card Number"
	case "4015":
		return "No such issuer"
	case "4016":
		return "Approved, Update Track 3"
	case "4017":
		return "Customer Cancellation"
	case "4018":
		return "Customer Dispute"
	case "4019":
		return "Re-enter Transaction"
	case "4020":
		return "Invalid Response"
	case "4021":
		return "No Action Taken"
	case "4022":
		return "Suspected Malfunction"
	case "4023":
		return "Unacceptable Transaction Fee"
	case "4024":
		return "File Update Not Supported by Receiver"
	case "4025":
		return "Unable to Locate Record on File"
	case "4026":
		return "Duplicate File Update Record"
	case "4027":
		return "File Update Field Edit Error"
	case "4028":
		return "File Update File Locked Out"
	case "4029":
		return "File Update not Successful"
	case "4030":
		return "Format Error"
	case "4031":
		return "Bank Not Supported by Switch"
	case "4032":
		return "Completed Partially"
	case "4033":
		return "Expired Card - Pick Up"
	case "4034":
		return "Suspected Fraud - Pick Up"
	case "4035":
		return "Restricted Card - Pick Up"
	case "4036":
		return "Allowable PIN Tries Exceeded"
	case "4037":
		return "No Credit Account"
	case "4038":
		return "Allowable PIN Tries Exceeded"
	case "4039":
		return "No Credit Account"
	case "4040":
		return "Requested Function not Supported"
	case "4041":
		return "Lost Card - Pick Up"
	case "4042":
		return "No Universal Amount"
	case "4043":
		return "Stolen Card - Pick Up"
	case "4044":
		return "No Investment Account"
	case "4045":
		return "Settlement Success"
	case "4046":
		return "Settlement Fail"
	case "4047":
		return "Cancel Success"
	case "4048":
		return "Cancel Fail"
	case "4049":
		return "No Transaction Reference Number"
	case "4050":
		return "Host Down"
	case "4051":
		return "Insufficient Funds"
	case "4052":
		return "No Cheque Account"
	case "4053":
		return "No Savings Account"
	case "4054":
		return "Expired Card"
	case "4055":
		return "Incorrect PIN"
	case "4056":
		return "No Card Record"
	case "4057":
		return "Transaction Not Permitted to Cardholder"
	case "4058":
		return "Transaction Not Permitted to Terminal"
	case "4059":
		return "Suspected Fraud"
	case "4060":
		return "Card Acceptor Contact Acquirer"
	case "4061":
		return "Exceeds Withdrawal Amount Limits"
	case "4062":
		return "Restricted Card"
	case "4063":
		return "Security Violation"
	case "4064":
		return "Original Amount Incorrect"
	case "4065":
		return "Exceeds Withdrawal Frequency Limit"
	case "4066":
		return "Card Acceptor Call Acquirer Security"
	case "4067":
		return "Hard Capture - Pick Up Card at ATM"
	case "4068":
		return "Response Received Too Late"
	case "4069":
		return "Reserved"
	case "4070":
		return "Settle amount cannot exceed authorized amount"
	case "4071":
		return "Inquiry Record Not Exist"
	case "4072":
		return "Promotion not allowed in current payment method"
	case "4073":
		return "Promotion Limit Reached"
	case "4074":
		return "Reserved"
	case "4075":
		return "Allowable PIN Tries Exceeded"
	case "4076":
		return "Invalid Credit Card Format"
	case "4077":
		return "Invalid Expiry Date Format"
	case "4078":
		return "Invalid Three Digits Format"
	case "4079":
		return "Reserved"
	case "4080":
		return "User Cancellation by Closing Internet Browser"
	case "4081":
		return "Unable to Authenticate Card Holder"
	case "4082":
		return "Reserved"
	case "4083":
		return "Reserved"
	case "4084":
		return "Reserved"
	case "4085":
		return "Reserved"
	case "4086":
		return "ATM Malfunction"
	case "4087":
		return "No Envelope Inserted"
	case "4088":
		return "Unable to Dispense"
	case "4089":
		return "Administration Error"
	case "4090":
		return "Cut-off in Progress"
	case "4091":
		return "Issuer or Switch is Inoperative"
	case "4092":
		return "Financial Insititution Not Found"
	case "4093":
		return "Trans Cannot Be Completed"
	case "4094":
		return "Duplicate Transmission"
	case "4095":
		return "Reconcile Error"
	case "4096":
		return "System Malfunction"
	case "4097":
		return "Reconciliation Totals Reset"
	case "4098":
		return "MAC Error"
	case "4099":
		return "Unable to Complete Payment"
	case "4110":
		return "Settled"
	case "4120":
		return "Refunded"
	case "4121":
		return "Refund Rejected"
	case "4122":
		return "Refund Failed"
	case "4130":
		return "Chargeback"
	case "4131":
		return "Chargeback Rejected"
	case "4132":
		return "Chargeback Failed"
	case "4140":
		return "Transaction Does Not Exist"
	case "4200":
		return "Tokenization Successful"
	case "4201":
		return "Tokenization Failed"
	case "4202":
		return "Invalid Card / Customer Token"
	case "4203":
		return "No response from account issuer"
	case "4204":
		return "Tokenization Action Failed (Token)"
	case "4205":
		return "Tokenization Action Failed (Limit Exceed)"
	case "4208":
		return "Tokenization Action Failed (Client)"
	case "4209":
		return "Tokenization Action Failed (Issuer)"
	case "5002":
		return "Timeout"
	case "5003":
		return "Invalid Message"
	case "5004":
		return "Invalid Profile (Merchant) ID"
	case "5005":
		return "Duplicated Invoice"
	case "5006":
		return "Invalid Amount"
	case "5007":
		return "Insufficient Balance"
	case "5008":
		return "Invalid Currency Code"
	case "5009":
		return "Payment Expired"
	case "5010":
		return "Payment Canceled By Payer"
	case "5011":
		return "Invalid Payee ID"
	case "5012":
		return "Invalid Customer ID"
	case "5013":
		return "Account Does Not Exist"
	case "5014":
		return "Authentication Failed"
	case "5015":
		return "Customer paid more than transaction amount"
	case "5016":
		return "Customer paid less than transaction amount"
	case "5017":
		return "Paid Expired"
	case "5018":
		return "Reserved"
	case "5019":
		return "No-Action From WebPay"
	case "5998":
		return "Internal Error"
	case "6012":
		return "Invalid Transaction"
	case "6101":
		return "Invalid request message"
	case "6102":
		return "Required Payload"
	case "6103":
		return "Invalid JWT data"
	case "6104":
		return "Required merchantId"
	case "6105":
		return "Required paymentChannel"
	case "6106":
		return "Required authCode"
	case "6107":
		return "Invalid merchantId"
	case "6108":
		return "Invalid paymentChannel"
	case "6109":
		return "paymentChannel is not configured"
	case "6110":
		return "Unable to retrieve usertoken"
	case "7012":
		return "Invalid Transaction"
	case "9004":
		return "The [ParameterName] value is not valid"
	case "9005":
		return "Some mandatory fields are missing"
	case "9006":
		return "This field exceeded its authorized length"
	case "9007":
		return "Invalid merchant"
	case "9008":
		return "Invalid payment expiry"
	case "9009":
		return "Amount is invalid"
	case "9010":
		return "Invalid Currency Code"
	case "9012":
		return "paymentItem name is required"
	case "9013":
		return "paymentItem quantity is required"
	case "9014":
		return "paymentItem amount is required"
	case "9015":
		return "Existing Invoice Number"
	case "9016":
		return "Failed to retrieve PaymentInstruction"
	case "9017":
		return "PaymentInstruction not available"
	case "9035":
		return "Payment failed"
	case "9037":
		return "Merchant configuration is missing"
	case "9038":
		return "Failed To Generate Token"
	case "9039":
		return "The merchant frontend URL is missing"
	case "9040":
		return "The token is invalid"
	case "9041":
		return "Payment token already used"
	case "9042":
		return "Hash value mismatch"
	case "9057":
		return "Payment options are invalid"
	case "9058":
		return "Payment channel invalid"
	case "9059":
		return "Payment channel unauthorized"
	case "9060":
		return "Payment channel unconfigured"
	case "9078":
		return "Promotion code does not exist"
	case "9080":
		return "Tokenization not allowed"
	case "9088":
		return "SubMerchant is required"
	case "9089":
		return "Duplicated SubMerchant"
	case "9090":
		return "SubMerchant Not Found"
	case "9091":
		return "Invalid Sub Merchant ID"
	case "9092":
		return "Invalid Sub Merchant invoiceNo"
	case "9093":
		return "Existing Sub Merchant Invoice Number"
	case "9094":
		return "Invalid Sub Merchant Amount"
	case "9095":
		return "Sub Merchant Amount mismatch"
	case "9100":
		return "FxRateId and OriginalAmount are required"
	case "9101":
		return "Not allow to make a payment with Fx"
	case "9102":
		return "FxRate not available"
	case "9103":
		return "Invalid amount. (for the transaction which using the FxRateId)"
	case "9104":
		return "Invalid Country Code (Airline Info)"
	case "9105":
		return "Invalid Currency Code (Airline Info)"
	case "9106":
		return "Invalid Loyalty Redeem Amount"
	case "9107":
		return "Invalid Loyalty Provider"
	case "9108":
		return "Duplicated Loyalty Reward Id"
	case "9109":
		return "Required Loyalty's External Merchant Id"
	case "9110":
		return "Failed to Inquiry Loyalty Rewards"
	case "9202":
		return "Invalid CustomerToken"
	case "9900":
		return "Unable to decrypt the payload"
	case "9901":
		return "Invalid invoicePrefix"
	case "9902":
		return "allowAccumulate is required"
	case "9903":
		return "maxAccumulateAmount is required"
	case "9904":
		return "recurringInterval or ChargeOnDate is required"
	case "9905":
		return "recurringCount is required"
	case "9906":
		return "recurringInterval or ChargeOnDate is required"
	case "9907":
		return "Invalid ChargeNextDate"
	case "9908":
		return "Invalid ChargeOnDate"
	case "9909":
		return "chargeNextDate is required"
	case "9990":
		return "Request to merchant front end has failed"
	case "9991":
		return "Request merchant secure has failed"
	case "9992":
		return "Request payment secure has failed"
	case "9993":
		return "An unknown error has occured"
	case "9994":
		return "Request DB service has failed"
	case "9995":
		return "Request payment service has failed"
	case "9996":
		return "Request Qwik service has failed"
	case "9997":
		return "Request user preferences has failed"
	case "9998":
		return "Request store card has failed"
	case "9999":
		return "Request to merchant backend has failed"
	default:
		return fmt.Sprintf("Unknown response code: %s", string(c))
	}
}

// Known response codes
const (
	Code0000Successful PaymentResponseCode = "0000" // Successful
	Code0001TransactionIsPending PaymentResponseCode = "0001" // Transaction is pending
	Code0003TransactionIsCancelled PaymentResponseCode = "0003" // Transaction is cancelled
	Code0004TransactionIsSoftdeclinedResubmitTheTransactionAfter3dsAuthentication PaymentResponseCode = "0004" // Transaction is soft-declined. Resubmit the transaction after 3ds authentication
	Code0999SystemError PaymentResponseCode = "0999" // System error
	Code2001TransactionInProgress PaymentResponseCode = "2001" // Transaction in progress
	Code2002TransactionNotFound PaymentResponseCode = "2002" // Transaction not found
	Code2003FailedToInquiry PaymentResponseCode = "2003" // Failed To Inquiry
	Code4000CardVerificationSuccessful PaymentResponseCode = "4000" // Card Verification Successful
	Code4001ReferToCardIssuer PaymentResponseCode = "4001" // Refer to card issuer
	Code4002ReferToIssuersSpecialConditions PaymentResponseCode = "4002" // Refer to issuer's special conditions
	Code4003InvalidMerchantId PaymentResponseCode = "4003" // Invalid merchant ID
	Code4004PickUpCard PaymentResponseCode = "4004" // Pick up card
	Code4005DoNotHonor PaymentResponseCode = "4005" // Do not honor
	Code4006Error PaymentResponseCode = "4006" // Error
	Code4007PickUpCardSpecialCondition PaymentResponseCode = "4007" // Pick up card, special condition
	Code4008HonorWithId PaymentResponseCode = "4008" // Honor with ID
	Code4009RequestInProgress PaymentResponseCode = "4009" // Request in progress
	Code4010PartialAmountApproved PaymentResponseCode = "4010" // Partial amount approved
	Code4011ApprovedVip PaymentResponseCode = "4011" // Approved VIP
	Code4012InvalidTransaction PaymentResponseCode = "4012" // Invalid Transaction
	Code4013InvalidAmount PaymentResponseCode = "4013" // Invalid Amount
	Code4014InvalidCardNumber PaymentResponseCode = "4014" // Invalid Card Number
	Code4015NoSuchIssuer PaymentResponseCode = "4015" // No such issuer
	Code4016ApprovedUpdateTrack3 PaymentResponseCode = "4016" // Approved, Update Track 3
	Code4017CustomerCancellation PaymentResponseCode = "4017" // Customer Cancellation
	Code4018CustomerDispute PaymentResponseCode = "4018" // Customer Dispute
	Code4019ReenterTransaction PaymentResponseCode = "4019" // Re-enter Transaction
	Code4020InvalidResponse PaymentResponseCode = "4020" // Invalid Response
	Code4021NoActionTaken PaymentResponseCode = "4021" // No Action Taken
	Code4022SuspectedMalfunction PaymentResponseCode = "4022" // Suspected Malfunction
	Code4023UnacceptableTransactionFee PaymentResponseCode = "4023" // Unacceptable Transaction Fee
	Code4024FileUpdateNotSupportedByReceiver PaymentResponseCode = "4024" // File Update Not Supported by Receiver
	Code4025UnableToLocateRecordOnFile PaymentResponseCode = "4025" // Unable to Locate Record on File
	Code4026DuplicateFileUpdateRecord PaymentResponseCode = "4026" // Duplicate File Update Record
	Code4027FileUpdateFieldEditError PaymentResponseCode = "4027" // File Update Field Edit Error
	Code4028FileUpdateFileLockedOut PaymentResponseCode = "4028" // File Update File Locked Out
	Code4029FileUpdateNotSuccessful PaymentResponseCode = "4029" // File Update not Successful
	Code4030FormatError PaymentResponseCode = "4030" // Format Error
	Code4031BankNotSupportedBySwitch PaymentResponseCode = "4031" // Bank Not Supported by Switch
	Code4032CompletedPartially PaymentResponseCode = "4032" // Completed Partially
	Code4033ExpiredCardPickUp PaymentResponseCode = "4033" // Expired Card - Pick Up
	Code4034SuspectedFraudPickUp PaymentResponseCode = "4034" // Suspected Fraud - Pick Up
	Code4035RestrictedCardPickUp PaymentResponseCode = "4035" // Restricted Card - Pick Up
	Code4036AllowablePinTriesExceeded PaymentResponseCode = "4036" // Allowable PIN Tries Exceeded
	Code4037NoCreditAccount PaymentResponseCode = "4037" // No Credit Account
	Code4038AllowablePinTriesExceeded PaymentResponseCode = "4038" // Allowable PIN Tries Exceeded
	Code4039NoCreditAccount PaymentResponseCode = "4039" // No Credit Account
	Code4040RequestedFunctionNotSupported PaymentResponseCode = "4040" // Requested Function not Supported
	Code4041LostCardPickUp PaymentResponseCode = "4041" // Lost Card - Pick Up
	Code4042NoUniversalAmount PaymentResponseCode = "4042" // No Universal Amount
	Code4043StolenCardPickUp PaymentResponseCode = "4043" // Stolen Card - Pick Up
	Code4044NoInvestmentAccount PaymentResponseCode = "4044" // No Investment Account
	Code4045SettlementSuccess PaymentResponseCode = "4045" // Settlement Success
	Code4046SettlementFail PaymentResponseCode = "4046" // Settlement Fail
	Code4047CancelSuccess PaymentResponseCode = "4047" // Cancel Success
	Code4048CancelFail PaymentResponseCode = "4048" // Cancel Fail
	Code4049NoTransactionReferenceNumber PaymentResponseCode = "4049" // No Transaction Reference Number
	Code4050HostDown PaymentResponseCode = "4050" // Host Down
	Code4051InsufficientFunds PaymentResponseCode = "4051" // Insufficient Funds
	Code4052NoChequeAccount PaymentResponseCode = "4052" // No Cheque Account
	Code4053NoSavingsAccount PaymentResponseCode = "4053" // No Savings Account
	Code4054ExpiredCard PaymentResponseCode = "4054" // Expired Card
	Code4055IncorrectPin PaymentResponseCode = "4055" // Incorrect PIN
	Code4056NoCardRecord PaymentResponseCode = "4056" // No Card Record
	Code4057TransactionNotPermittedToCardholder PaymentResponseCode = "4057" // Transaction Not Permitted to Cardholder
	Code4058TransactionNotPermittedToTerminal PaymentResponseCode = "4058" // Transaction Not Permitted to Terminal
	Code4059SuspectedFraud PaymentResponseCode = "4059" // Suspected Fraud
	Code4060CardAcceptorContactAcquirer PaymentResponseCode = "4060" // Card Acceptor Contact Acquirer
	Code4061ExceedsWithdrawalAmountLimits PaymentResponseCode = "4061" // Exceeds Withdrawal Amount Limits
	Code4062RestrictedCard PaymentResponseCode = "4062" // Restricted Card
	Code4063SecurityViolation PaymentResponseCode = "4063" // Security Violation
	Code4064OriginalAmountIncorrect PaymentResponseCode = "4064" // Original Amount Incorrect
	Code4065ExceedsWithdrawalFrequencyLimit PaymentResponseCode = "4065" // Exceeds Withdrawal Frequency Limit
	Code4066CardAcceptorCallAcquirerSecurity PaymentResponseCode = "4066" // Card Acceptor Call Acquirer Security
	Code4067HardCapturePickUpCardAtAtm PaymentResponseCode = "4067" // Hard Capture - Pick Up Card at ATM
	Code4068ResponseReceivedTooLate PaymentResponseCode = "4068" // Response Received Too Late
	Code4069Reserved PaymentResponseCode = "4069" // Reserved
	Code4070SettleAmountCannotExceedAuthorizedAmount PaymentResponseCode = "4070" // Settle amount cannot exceed authorized amount
	Code4071InquiryRecordNotExist PaymentResponseCode = "4071" // Inquiry Record Not Exist
	Code4072PromotionNotAllowedInCurrentPaymentMethod PaymentResponseCode = "4072" // Promotion not allowed in current payment method
	Code4073PromotionLimitReached PaymentResponseCode = "4073" // Promotion Limit Reached
	Code4074Reserved PaymentResponseCode = "4074" // Reserved
	Code4075AllowablePinTriesExceeded PaymentResponseCode = "4075" // Allowable PIN Tries Exceeded
	Code4076InvalidCreditCardFormat PaymentResponseCode = "4076" // Invalid Credit Card Format
	Code4077InvalidExpiryDateFormat PaymentResponseCode = "4077" // Invalid Expiry Date Format
	Code4078InvalidThreeDigitsFormat PaymentResponseCode = "4078" // Invalid Three Digits Format
	Code4079Reserved PaymentResponseCode = "4079" // Reserved
	Code4080UserCancellationByClosingInternetBrowser PaymentResponseCode = "4080" // User Cancellation by Closing Internet Browser
	Code4081UnableToAuthenticateCardHolder PaymentResponseCode = "4081" // Unable to Authenticate Card Holder
	Code4082Reserved PaymentResponseCode = "4082" // Reserved
	Code4083Reserved PaymentResponseCode = "4083" // Reserved
	Code4084Reserved PaymentResponseCode = "4084" // Reserved
	Code4085Reserved PaymentResponseCode = "4085" // Reserved
	Code4086AtmMalfunction PaymentResponseCode = "4086" // ATM Malfunction
	Code4087NoEnvelopeInserted PaymentResponseCode = "4087" // No Envelope Inserted
	Code4088UnableToDispense PaymentResponseCode = "4088" // Unable to Dispense
	Code4089AdministrationError PaymentResponseCode = "4089" // Administration Error
	Code4090CutoffInProgress PaymentResponseCode = "4090" // Cut-off in Progress
	Code4091IssuerOrSwitchIsInoperative PaymentResponseCode = "4091" // Issuer or Switch is Inoperative
	Code4092FinancialInsititutionNotFound PaymentResponseCode = "4092" // Financial Insititution Not Found
	Code4093TransCannotBeCompleted PaymentResponseCode = "4093" // Trans Cannot Be Completed
	Code4094DuplicateTransmission PaymentResponseCode = "4094" // Duplicate Transmission
	Code4095ReconcileError PaymentResponseCode = "4095" // Reconcile Error
	Code4096SystemMalfunction PaymentResponseCode = "4096" // System Malfunction
	Code4097ReconciliationTotalsReset PaymentResponseCode = "4097" // Reconciliation Totals Reset
	Code4098MacError PaymentResponseCode = "4098" // MAC Error
	Code4099UnableToCompletePayment PaymentResponseCode = "4099" // Unable to Complete Payment
	Code4110Settled PaymentResponseCode = "4110" // Settled
	Code4120Refunded PaymentResponseCode = "4120" // Refunded
	Code4121RefundRejected PaymentResponseCode = "4121" // Refund Rejected
	Code4122RefundFailed PaymentResponseCode = "4122" // Refund Failed
	Code4130Chargeback PaymentResponseCode = "4130" // Chargeback
	Code4131ChargebackRejected PaymentResponseCode = "4131" // Chargeback Rejected
	Code4132ChargebackFailed PaymentResponseCode = "4132" // Chargeback Failed
	Code4140TransactionDoesNotExist PaymentResponseCode = "4140" // Transaction Does Not Exist
	Code4200TokenizationSuccessful PaymentResponseCode = "4200" // Tokenization Successful
	Code4201TokenizationFailed PaymentResponseCode = "4201" // Tokenization Failed
	Code4202InvalidCardCustomerToken PaymentResponseCode = "4202" // Invalid Card / Customer Token
	Code4203NoResponseFromAccountIssuer PaymentResponseCode = "4203" // No response from account issuer
	Code4204TokenizationActionFailedToken PaymentResponseCode = "4204" // Tokenization Action Failed (Token)
	Code4205TokenizationActionFailedLimitExceed PaymentResponseCode = "4205" // Tokenization Action Failed (Limit Exceed)
	Code4208TokenizationActionFailedClient PaymentResponseCode = "4208" // Tokenization Action Failed (Client)
	Code4209TokenizationActionFailedIssuer PaymentResponseCode = "4209" // Tokenization Action Failed (Issuer)
	Code5002Timeout PaymentResponseCode = "5002" // Timeout
	Code5003InvalidMessage PaymentResponseCode = "5003" // Invalid Message
	Code5004InvalidProfileMerchantId PaymentResponseCode = "5004" // Invalid Profile (Merchant) ID
	Code5005DuplicatedInvoice PaymentResponseCode = "5005" // Duplicated Invoice
	Code5006InvalidAmount PaymentResponseCode = "5006" // Invalid Amount
	Code5007InsufficientBalance PaymentResponseCode = "5007" // Insufficient Balance
	Code5008InvalidCurrencyCode PaymentResponseCode = "5008" // Invalid Currency Code
	Code5009PaymentExpired PaymentResponseCode = "5009" // Payment Expired
	Code5010PaymentCanceledByPayer PaymentResponseCode = "5010" // Payment Canceled By Payer
	Code5011InvalidPayeeId PaymentResponseCode = "5011" // Invalid Payee ID
	Code5012InvalidCustomerId PaymentResponseCode = "5012" // Invalid Customer ID
	Code5013AccountDoesNotExist PaymentResponseCode = "5013" // Account Does Not Exist
	Code5014AuthenticationFailed PaymentResponseCode = "5014" // Authentication Failed
	Code5015CustomerPaidMoreThanTransactionAmount PaymentResponseCode = "5015" // Customer paid more than transaction amount
	Code5016CustomerPaidLessThanTransactionAmount PaymentResponseCode = "5016" // Customer paid less than transaction amount
	Code5017PaidExpired PaymentResponseCode = "5017" // Paid Expired
	Code5018Reserved PaymentResponseCode = "5018" // Reserved
	Code5019NoactionFromWebpay PaymentResponseCode = "5019" // No-Action From WebPay
	Code5998InternalError PaymentResponseCode = "5998" // Internal Error
	Code6012InvalidTransaction PaymentResponseCode = "6012" // Invalid Transaction
	Code6101InvalidRequestMessage PaymentResponseCode = "6101" // Invalid request message
	Code6102RequiredPayload PaymentResponseCode = "6102" // Required Payload
	Code6103InvalidJwtData PaymentResponseCode = "6103" // Invalid JWT data
	Code6104RequiredMerchantid PaymentResponseCode = "6104" // Required merchantId
	Code6105RequiredPaymentchannel PaymentResponseCode = "6105" // Required paymentChannel
	Code6106RequiredAuthcode PaymentResponseCode = "6106" // Required authCode
	Code6107InvalidMerchantid PaymentResponseCode = "6107" // Invalid merchantId
	Code6108InvalidPaymentchannel PaymentResponseCode = "6108" // Invalid paymentChannel
	Code6109PaymentchannelIsNotConfigured PaymentResponseCode = "6109" // paymentChannel is not configured
	Code6110UnableToRetrieveUsertoken PaymentResponseCode = "6110" // Unable to retrieve usertoken
	Code7012InvalidTransaction PaymentResponseCode = "7012" // Invalid Transaction
	Code9004TheParameternameValueIsNotValid PaymentResponseCode = "9004" // The [ParameterName] value is not valid
	Code9005SomeMandatoryFieldsAreMissing PaymentResponseCode = "9005" // Some mandatory fields are missing
	Code9006ThisFieldExceededItsAuthorizedLength PaymentResponseCode = "9006" // This field exceeded its authorized length
	Code9007InvalidMerchant PaymentResponseCode = "9007" // Invalid merchant
	Code9008InvalidPaymentExpiry PaymentResponseCode = "9008" // Invalid payment expiry
	Code9009AmountIsInvalid PaymentResponseCode = "9009" // Amount is invalid
	Code9010InvalidCurrencyCode PaymentResponseCode = "9010" // Invalid Currency Code
	Code9012PaymentitemNameIsRequired PaymentResponseCode = "9012" // paymentItem name is required
	Code9013PaymentitemQuantityIsRequired PaymentResponseCode = "9013" // paymentItem quantity is required
	Code9014PaymentitemAmountIsRequired PaymentResponseCode = "9014" // paymentItem amount is required
	Code9015ExistingInvoiceNumber PaymentResponseCode = "9015" // Existing Invoice Number
	Code9016FailedToRetrievePaymentinstruction PaymentResponseCode = "9016" // Failed to retrieve PaymentInstruction
	Code9017PaymentinstructionNotAvailable PaymentResponseCode = "9017" // PaymentInstruction not available
	Code9035PaymentFailed PaymentResponseCode = "9035" // Payment failed
	Code9037MerchantConfigurationIsMissing PaymentResponseCode = "9037" // Merchant configuration is missing
	Code9038FailedToGenerateToken PaymentResponseCode = "9038" // Failed To Generate Token
	Code9039TheMerchantFrontendUrlIsMissing PaymentResponseCode = "9039" // The merchant frontend URL is missing
	Code9040TheTokenIsInvalid PaymentResponseCode = "9040" // The token is invalid
	Code9041PaymentTokenAlreadyUsed PaymentResponseCode = "9041" // Payment token already used
	Code9042HashValueMismatch PaymentResponseCode = "9042" // Hash value mismatch
	Code9057PaymentOptionsAreInvalid PaymentResponseCode = "9057" // Payment options are invalid
	Code9058PaymentChannelInvalid PaymentResponseCode = "9058" // Payment channel invalid
	Code9059PaymentChannelUnauthorized PaymentResponseCode = "9059" // Payment channel unauthorized
	Code9060PaymentChannelUnconfigured PaymentResponseCode = "9060" // Payment channel unconfigured
	Code9078PromotionCodeDoesNotExist PaymentResponseCode = "9078" // Promotion code does not exist
	Code9080TokenizationNotAllowed PaymentResponseCode = "9080" // Tokenization not allowed
	Code9088SubmerchantIsRequired PaymentResponseCode = "9088" // SubMerchant is required
	Code9089DuplicatedSubmerchant PaymentResponseCode = "9089" // Duplicated SubMerchant
	Code9090SubmerchantNotFound PaymentResponseCode = "9090" // SubMerchant Not Found
	Code9091InvalidSubMerchantId PaymentResponseCode = "9091" // Invalid Sub Merchant ID
	Code9092InvalidSubMerchantInvoiceno PaymentResponseCode = "9092" // Invalid Sub Merchant invoiceNo
	Code9093ExistingSubMerchantInvoiceNumber PaymentResponseCode = "9093" // Existing Sub Merchant Invoice Number
	Code9094InvalidSubMerchantAmount PaymentResponseCode = "9094" // Invalid Sub Merchant Amount
	Code9095SubMerchantAmountMismatch PaymentResponseCode = "9095" // Sub Merchant Amount mismatch
	Code9100FxrateidAndOriginalamountAreRequired PaymentResponseCode = "9100" // FxRateId and OriginalAmount are required
	Code9101NotAllowToMakeAPaymentWithFx PaymentResponseCode = "9101" // Not allow to make a payment with Fx
	Code9102FxrateNotAvailable PaymentResponseCode = "9102" // FxRate not available
	Code9103InvalidAmountForTheTransactionWhichUsingTheFxrateid PaymentResponseCode = "9103" // Invalid amount. (for the transaction which using the FxRateId)
	Code9104InvalidCountryCodeAirlineInfo PaymentResponseCode = "9104" // Invalid Country Code (Airline Info)
	Code9105InvalidCurrencyCodeAirlineInfo PaymentResponseCode = "9105" // Invalid Currency Code (Airline Info)
	Code9106InvalidLoyaltyRedeemAmount PaymentResponseCode = "9106" // Invalid Loyalty Redeem Amount
	Code9107InvalidLoyaltyProvider PaymentResponseCode = "9107" // Invalid Loyalty Provider
	Code9108DuplicatedLoyaltyRewardId PaymentResponseCode = "9108" // Duplicated Loyalty Reward Id
	Code9109RequiredLoyaltysExternalMerchantId PaymentResponseCode = "9109" // Required Loyalty's External Merchant Id
	Code9110FailedToInquiryLoyaltyRewards PaymentResponseCode = "9110" // Failed to Inquiry Loyalty Rewards
	Code9202InvalidCustomertoken PaymentResponseCode = "9202" // Invalid CustomerToken
	Code9900UnableToDecryptThePayload PaymentResponseCode = "9900" // Unable to decrypt the payload
	Code9901InvalidInvoiceprefix PaymentResponseCode = "9901" // Invalid invoicePrefix
	Code9902AllowaccumulateIsRequired PaymentResponseCode = "9902" // allowAccumulate is required
	Code9903MaxaccumulateamountIsRequired PaymentResponseCode = "9903" // maxAccumulateAmount is required
	Code9904RecurringintervalOrChargeondateIsRequired PaymentResponseCode = "9904" // recurringInterval or ChargeOnDate is required
	Code9905RecurringcountIsRequired PaymentResponseCode = "9905" // recurringCount is required
	Code9906RecurringintervalOrChargeondateIsRequired PaymentResponseCode = "9906" // recurringInterval or ChargeOnDate is required
	Code9907InvalidChargenextdate PaymentResponseCode = "9907" // Invalid ChargeNextDate
	Code9908InvalidChargeondate PaymentResponseCode = "9908" // Invalid ChargeOnDate
	Code9909ChargenextdateIsRequired PaymentResponseCode = "9909" // chargeNextDate is required
	Code9990RequestToMerchantFrontEndHasFailed PaymentResponseCode = "9990" // Request to merchant front end has failed
	Code9991RequestMerchantSecureHasFailed PaymentResponseCode = "9991" // Request merchant secure has failed
	Code9992RequestPaymentSecureHasFailed PaymentResponseCode = "9992" // Request payment secure has failed
	Code9993AnUnknownErrorHasOccured PaymentResponseCode = "9993" // An unknown error has occured
	Code9994RequestDbServiceHasFailed PaymentResponseCode = "9994" // Request DB service has failed
	Code9995RequestPaymentServiceHasFailed PaymentResponseCode = "9995" // Request payment service has failed
	Code9996RequestQwikServiceHasFailed PaymentResponseCode = "9996" // Request Qwik service has failed
	Code9997RequestUserPreferencesHasFailed PaymentResponseCode = "9997" // Request user preferences has failed
	Code9998RequestStoreCardHasFailed PaymentResponseCode = "9998" // Request store card has failed
	Code9999RequestToMerchantBackendHasFailed PaymentResponseCode = "9999" // Request to merchant backend has failed
)
